server:
  port: 8082
  
spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true 
        
  application:
    name: employeeService
    
  datasource:
    url: jdbc:h2:mem:testdb
    

